# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\screen3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QHeaderView


class TestScreen3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_fcm = QtWidgets.QWidget()
        self.page_fcm.setObjectName("page_fcm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_fcm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackWidget_fcm = QtWidgets.QStackedWidget(self.page_fcm)
        self.stackWidget_fcm.setObjectName("stackWidget_fcm")
        self.page_fcm_eval = QtWidgets.QWidget()
        self.page_fcm_eval.setObjectName("page_fcm_eval")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_fcm_eval)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_fcm_eval = QtWidgets.QTableWidget(self.page_fcm_eval)
        self.table_fcm_eval.setObjectName("table_fcm_eval")
        self.table_fcm_eval.setColumnCount(0)
        self.table_fcm_eval.setRowCount(0)
        self.gridLayout_3.addWidget(self.table_fcm_eval, 0, 0, 1, 1)
        self.stackWidget_fcm.addWidget(self.page_fcm_eval)
        self.page_fcm_U = QtWidgets.QWidget()
        self.page_fcm_U.setObjectName("page_fcm_U")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_fcm_U)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.table_fcm_U = QtWidgets.QTableWidget(self.page_fcm_U)
        self.table_fcm_U.setObjectName("table_fcm_U")
        self.table_fcm_U.setColumnCount(0)
        self.table_fcm_U.setRowCount(0)
        self.gridLayout_6.addWidget(self.table_fcm_U, 0, 0, 1, 1)
        self.stackWidget_fcm.addWidget(self.page_fcm_U)
        self.page_fcm_V = QtWidgets.QWidget()
        self.page_fcm_V.setObjectName("page_fcm_V")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_fcm_V)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.table_fcm_V = QtWidgets.QTableWidget(self.page_fcm_V)
        self.table_fcm_V.setObjectName("table_fcm_V")
        self.table_fcm_V.setColumnCount(0)
        self.table_fcm_V.setRowCount(0)
        self.gridLayout_7.addWidget(self.table_fcm_V, 0, 0, 1, 1)
        self.stackWidget_fcm.addWidget(self.page_fcm_V)
        self.gridLayout_2.addWidget(self.stackWidget_fcm, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_fcm)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_5.addWidget(self.stackedWidget, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 627, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.table_fcm_eval.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        # self.table_fcm_V.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        # self.table_fcm_U.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.add()

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Thuật toán"))
        self.pushButton.setText(_translate("MainWindow", "FCM"))
        self.pushButton_2.setText(_translate("MainWindow", "MC-FCM"))
        self.pushButton_3.setText(_translate("MainWindow", "sSMC-FCM"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p>Thuật toán: FCM</p><p>Đầu ra: Độ đo hiệu năng</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Đầu ra"))
        self.pushButton_4.setText(_translate("MainWindow", "Độ đo hiệu năng"))
        self.pushButton_6.setText(_translate("MainWindow", "V"))
        self.pushButton_5.setText(_translate("MainWindow", "U"))

    def add(self):
        self.pushButton.clicked.connect(self.pushFCM)
        # self.pushButton_2.clicked.connect(self.pushMCFCM)
        # self.pushButton_3.clicked.connect(self.pushsSMCFCM)
        self.pushButton_4.clicked.connect(self.pushEval)
        self.pushButton_5.clicked.connect(self.pushU)
        self.pushButton_6.clicked.connect(self.pushV)

    def loadData(self, data_table, tableWidget):
        max_row = len(data_table)
        max_col = len(data_table[0])
        tableWidget.setRowCount(max_row)
        tableWidget.setColumnCount(max_col)
        for row in range(max_row):
            for col in range(max_col):
                tableWidget.setItem(row, col, QTableWidgetItem(str(round(data_table[row][col], 9))))

    def loadDataFCM(self, U, V, evalList):
        self.loadData(U, self.table_fcm_U)
        self.loadData(V, self.table_fcm_V)
        self.loadData(evalList, self.table_fcm_eval)
        self.table_fcm_eval.setVerticalHeaderLabels(['Rand Index',
                                                     'Davies-Bouldin Index',
                                                     'PBM index',
                                                     'Alternative Silhouette Width Criterion',
                                                     'Mean accuracy'])

    def loadDataMCFCM(self,U, V, evalList):
        self.loadData(U, self.table_fcm_U)
        self.loadData(V, self.table_fcm_V)
        self.loadData(evalList, self.table_fcm_eval)
        self.table_fcm_eval.setVerticalHeaderLabels(['Rand Index',
                                                     'Davies-Bouldin Index',
                                                     'PBM index',
                                                     'Alternative Silhouette Width Criterion',
                                                     'Mean accuracy'])

    def pushFCM(self):
        self.stackedWidget.setCurrentWidget(self.stackWidget_fcm)
        self.stackedWidget.setCurrentIndex(0)

    def pushEval(self):
        widget = self.stackedWidget.currentIndex()
        if widget == 0:
            self.stackWidget_fcm.setCurrentWidget(self.page_fcm_eval)


    def pushU(self):
        widget = self.stackedWidget.currentIndex()
        if widget == 0:
            self.stackWidget_fcm.setCurrentWidget(self.page_fcm_U)

    def pushV(self):
        widget = self.stackedWidget.currentIndex()
        if widget == 0:
            self.stackWidget_fcm.setCurrentWidget(self.page_fcm_V)


    def pushMCFCM(self):
        pass
